### ISSUE TITLE
Local declaration of criticalness

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/n-ui#261]
As mentioned https://github.com/Financial-Times/n-ui/issues/246#issuecomment-232702054The problem with this is that if we have

``` sass
@import 'n-ui/buttons/main';
@include nUiCriticalStart();
@import 'n-ui/buttons/main';
@include nUiCriticalEnd();
```

Then button will not be included in head.css as the first @import of buttons is the only one that outputs something

Your solutions below 😄

**Comment by i-like-robots** [comment]
This is a limitation of markup languages in general so I'm inclined to believe that there is no amount of pre or post processing that can be thrown at it to solve it satisfactorily. Off the top of my head I have some ideas - consider these pub chat rather than well considered 🍺:

## Use the things we've already built to deliver a shared CSS bundle

Cache hits === perf. Users who visit multiple pages will go into perf negative with the current inlined CSS, this way they probably wouldn't. After hitting the first page everything else would be 🚅

## Only consider the header and navigation as critical and hide the rest

The page isn't actually usable on first render, it's an illusion of speed. I have a feeling this will still make the site appear to be blazing fast. We could use `visibility: hidden` on the remainder of the page until the main stylesheet is loaded.

## Automate it

Obviously previously considered but due to the bazillion variations of each page, crazy tricky. The manual approach however is both fiddly (configuration) and relatively inefficient (we have to be over zealous in the amount of styles we inline). Automation avoids the issue you've raised even if it does bring up many others.

**Comment by wheresrhys** [comment]
option 2 has a nice feel to it. maybe option 2, + skeleton style + (for article only) enough to style the heading, standfirst and byline without shifting content around later

option 2 could also help with the perception if ads being slow to load -we could do some ad kickoff stuff when the page is still blank @adgad 🙉

**Comment by wheresrhys** [comment]
I agree automation gives the best results, but probably vulnerable - - due to masses of feature flags etc - to monumental cock-ups

**Comment by wheresrhys** [comment]
my one idea so far is to not output anything from n-ui components directly. Instead, at the end of the stylesheet call `nUiOutput()` , which sees what's been requested adn outputs appropriately. Vulnerable to style rule order e.g. an artiicle variant `o-butttons--wahey` would get overridden by o-buttons defaults

So not a workable solution, but putting it out there in case someone else can make it work.

**Comment by wheresrhys** [comment]
hmmm, maybe they output comments always and then build tooling does the job of moving the style block around?

**Comment by ironsidevsquincy** [comment]
Or maybe turn off 'output once' of modules and let the minifier do its thing?
We'd need to create a plugin which runs after the concatenation but before the minification process to move the any critical markers to the beginning of the file, e.g.

```
/*! start:head.css*/
.foo {
    color :red;
}
/*! start:end.css*/

.bar {
    color: green;
}

/*! start:head.css*/
.bar {
    color :blue;
}
/*! start:end.css*/
```

becomes

```
/*! start:head.css*/
.foo {
    color :red;
}
/*! start:end.css*/

/*! start:head.css*/
.bar {
    color :blue;
}
/*! start:end.css*/

.bar {
    color: green;
}
```

And after minification becomes

```
/*! start:head.css*/
.foo {
    color :red;
}
/*! start:end.css*/

/*! start:head.css*/
.bar {
    color :blue;
}
/*! start:end.css*/
```

**Comment by wheresrhys** [comment]
Or something similar where 

```
/*! start-component: foo *//*! start:head.css*/
.foo {
    color :red;
}
/*! end-component: foo *//*! start:end.css*/

/*! start-component: bar */
.bar {
    color: green;
}
/*! end-component: bar */
/*! start-component: bar *//*! start:head.css*/
.bar {
    color :blue;
}
/*! end-component: bar *//*! start:end.css*/
```

then a build rule like (pseudo code)

```
if (matches(/*! start-component: bar *//*! start:head.css*/)) {
  replaceGlobally(/*! start-component: bar */, /*! start-component: bar *//*! start:head.css*/)
}
```

**Comment by i-like-robots** [comment]
Moving CSS blocks around will change the cascade as authored which may cause unexpected side effects - particularly in production where these optimisations generally take place. Such processes would have to be in place in development too.

**Comment by i-like-robots** [comment]
A better option may be to make multiple passes of the Sass compiler instead instead of plucking out blocks post transpilation - just as we do for the separate old IE stylesheet.

```scss
// head.scss
$n-ui-critical: true;
@import 'main';

// body.scss
$n-ui-critical: false;
@import 'main';

// sass-utils/_functions.scss
@function nUiApply($module-name, $partial-name: '') {
	@if nUiHas($module-name) {
		$full-name: $module-name + $partial-name;
		$should-apply: index($n-ui-imported-modules, $full-name) == null and if($n-ui-critical, nUiFeatureValue($module-name) == 'critical', true);

		@if ($should-apply) {
			$n-ui-imported-modules: append($n-ui-imported-modules, $full-name) !global;
		}

		@return $should-apply;
	}

	@return false;
}
```
